language: ruby
rvm:
 - 2.5.1
services:
 - postgresql
before_script:
 - psql -c 'create database minskrb_test;' -U postgres
 - yarn install
 - RAILS_ENV=test bundle exec rails webpacker:compile
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true