version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - ./data:/var/data/redis
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/minskrb_app
    depends_on:
      - db
      - redis
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/minskrb_app
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
  # web:
  #   image: umputun/nginx-le:latest
  #   hostname: nginx
  #   restart: always
  #   logging:
  #     driver: json-file
  #     options:
  #         max-size: "10m"
  #         max-file: "5"
  #   volumes:
  #       - ./etc/ssl:/etc/nginx/ssl
  #       - ./config/nginx.conf:/etc/nginx/service.conf
  #   ports:
  #     - "443:80"
  #   environment:
  #       - TZ=Europe/Minsk
  #       - LETSENCRYPT=true
  #       - LE_EMAIL=zhenia.zhak@gmail.com
  #       - LE_FQDN=localhost
  #   depends_on:
  #     - app
