version: '3'

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: minskrb_development

  app:
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: minskrb_development

    build:
      args:
        BRANCH: "feature/dockerize"
        REPOSITORY: https://github.com/minskrb/minskrb.git

  sidekiq:
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: minskrb_development

    build:
      args:
        BRANCH: "feature/dockerize"
        REPOSITORY: https://github.com/minskrb/minskrb.git

  nginx:
    environment:
      - TZ=Europe/Minsk
      - LETSENCRYPT=false
      - LE_EMAIL=zhenia.zhak@gmail.com
      - LE_FQDN=localhost

    build:
        args:
          env: dev
