version: '3'

services:
  #db:
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: example
  #    POSTGRES_DB: minskrb_development

  app:
    environment:
      - RAILS_ENV=production
  #    POSTGRES_HOST: db
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: example
  #    POSTGRES_DB: minskrb_development

    build:
      args:
        RAILS_ENV: production
        BRANCH: "feature/dockerize"
        REPOSITORY: https://github.com/minskrb/minskrb.git

  sidekiq:
  #  environment:
  #    POSTGRES_HOST: db
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: example
  #    POSTGRES_DB: minskrb_development

    build:
      args:
        BRANCH: "feature/dockerize"
        REPOSITORY: https://github.com/minskrb/minskrb.git

  nginx:
    environment:
      - TZ=Europe/Minsk
      - LETSENCRYPT=true
      - LE_EMAIL=zhenia.zhak@gmail.com
      - LE_FQDN=minskrb.community

    build:
        args:
          env: prod
