version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - ./data:/var/data/redis

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: on-failure

  sidekiq:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - ./public:/app/public
    restart: on-failure
    env_file:
      - .env

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./tmp/sockets:/sockets
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
